version: '3.8'

services:
  # VM 1 (dist001)
  broker:
    build: .
    container_name: distrieats-broker
    network_mode: "host"
    environment:
      - CSV_FILE=${CSV_FILE:-pedidos.csv}
    command: ["sh", "-c", "./broker --port=50050 --datanodes=${DATANODES_ADDRESS:-dist002.inf.santiago.usm.cl:50051,dist003.inf.santiago.usm.cl:50052,dist004.inf.santiago.usm.cl:50053} --csv=$$CSV_FILE"]

  # VM 2 (dist002)
  gateway:
    build: .
    container_name: distrieats-gateway
    network_mode: "host"
    command: ["./gateway", "--port=50040", "--broker=${BROKER_ADDRESS:-dist001.inf.santiago.usm.cl:50050}", "--datanodes=${DATANODES_ADDRESS:-dist002.inf.santiago.usm.cl:50051,dist003.inf.santiago.usm.cl:50052,dist004.inf.santiago.usm.cl:50053}"]

  datanode1:
    build: .
    container_name: distrieats-datanode1
    network_mode: "host"
    command: ["./datanode", "--id=DN1", "--port=50051", "--peers=${PEERS_DN1:-dist003.inf.santiago.usm.cl:50052,dist004.inf.santiago.usm.cl:50053}"]

  cliente1:
    build: .
    container_name: distrieats-cliente1
    network_mode: "host"
    command: ["./client", "--gateway=${GATEWAY_ADDRESS:-dist002.inf.santiago.usm.cl:50040}", "--client=Cliente-1", "--pedido=${PEDIDO_C1:-Ped-001}"]

  # VM 3 (dist003)
  datanode2:
    build: .
    container_name: distrieats-datanode2
    network_mode: "host"
    command: ["./datanode", "--id=DN2", "--port=50052", "--peers=${PEERS_DN2:-dist002.inf.santiago.usm.cl:50051,dist004.inf.santiago.usm.cl:50053}"]

  cliente2:
    build: .
    container_name: distrieats-cliente2
    network_mode: "host"
    command: ["./client", "--gateway=${GATEWAY_ADDRESS:-dist002.inf.santiago.usm.cl:50040}", "--client=Cliente-2", "--pedido=${PEDIDO_C2:-Ped-002}"]

  # VM 4 (dist004)
  datanode3:
    build: .
    container_name: distrieats-datanode3
    network_mode: "host"
    command: ["./datanode", "--id=DN3", "--port=50053", "--peers=${PEERS_DN3:-dist002.inf.santiago.usm.cl:50051,dist003.inf.santiago.usm.cl:50052}"]

  cliente3:
    build: .
    container_name: distrieats-cliente3
    network_mode: "host"
    command: ["./client", "--gateway=${GATEWAY_ADDRESS:-dist002.inf.santiago.usm.cl:50040}", "--client=Cliente-3", "--pedido=${PEDIDO_C3:-Ped-003}"]
