// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: proto/distrieats.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientService_CrearPedido_FullMethodName     = "/distrieats.ClientService/CrearPedido"
	ClientService_ConsultarEstado_FullMethodName = "/distrieats.ClientService/ConsultarEstado"
)

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientServiceClient interface {
	// Operación de Escritura (Read Your Writes)
	CrearPedido(ctx context.Context, in *CrearPedidoRequest, opts ...grpc.CallOption) (*CrearPedidoResponse, error)
	// Operación de Lectura
	ConsultarEstado(ctx context.Context, in *ConsultarEstadoRequest, opts ...grpc.CallOption) (*ConsultarEstadoResponse, error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) CrearPedido(ctx context.Context, in *CrearPedidoRequest, opts ...grpc.CallOption) (*CrearPedidoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrearPedidoResponse)
	err := c.cc.Invoke(ctx, ClientService_CrearPedido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) ConsultarEstado(ctx context.Context, in *ConsultarEstadoRequest, opts ...grpc.CallOption) (*ConsultarEstadoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarEstadoResponse)
	err := c.cc.Invoke(ctx, ClientService_ConsultarEstado_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
// All implementations must embed UnimplementedClientServiceServer
// for forward compatibility.
type ClientServiceServer interface {
	// Operación de Escritura (Read Your Writes)
	CrearPedido(context.Context, *CrearPedidoRequest) (*CrearPedidoResponse, error)
	// Operación de Lectura
	ConsultarEstado(context.Context, *ConsultarEstadoRequest) (*ConsultarEstadoResponse, error)
	mustEmbedUnimplementedClientServiceServer()
}

// UnimplementedClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientServiceServer struct{}

func (UnimplementedClientServiceServer) CrearPedido(context.Context, *CrearPedidoRequest) (*CrearPedidoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearPedido not implemented")
}
func (UnimplementedClientServiceServer) ConsultarEstado(context.Context, *ConsultarEstadoRequest) (*ConsultarEstadoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarEstado not implemented")
}
func (UnimplementedClientServiceServer) mustEmbedUnimplementedClientServiceServer() {}
func (UnimplementedClientServiceServer) testEmbeddedByValue()                       {}

// UnsafeClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServiceServer will
// result in compilation errors.
type UnsafeClientServiceServer interface {
	mustEmbedUnimplementedClientServiceServer()
}

func RegisterClientServiceServer(s grpc.ServiceRegistrar, srv ClientServiceServer) {
	// If the following call panics, it indicates UnimplementedClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientService_ServiceDesc, srv)
}

func _ClientService_CrearPedido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearPedidoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).CrearPedido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_CrearPedido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).CrearPedido(ctx, req.(*CrearPedidoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_ConsultarEstado_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarEstadoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).ConsultarEstado(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_ConsultarEstado_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).ConsultarEstado(ctx, req.(*ConsultarEstadoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientService_ServiceDesc is the grpc.ServiceDesc for ClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distrieats.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrearPedido",
			Handler:    _ClientService_CrearPedido_Handler,
		},
		{
			MethodName: "ConsultarEstado",
			Handler:    _ClientService_ConsultarEstado_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/distrieats.proto",
}

const (
	DatanodeService_UpdateOrder_FullMethodName = "/distrieats.DatanodeService/UpdateOrder"
	DatanodeService_GetOrder_FullMethodName    = "/distrieats.DatanodeService/GetOrder"
	DatanodeService_GossipSync_FullMethodName  = "/distrieats.DatanodeService/GossipSync"
)

// DatanodeServiceClient is the client API for DatanodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatanodeServiceClient interface {
	// El Broker o el Gateway envían actualizaciones a un Datanode
	UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*UpdateOrderResponse, error)
	// El Gateway lee el estado desde un Datanode específico
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	// Sincronización entre pares (Gossip)
	GossipSync(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*GossipResponse, error)
}

type datanodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatanodeServiceClient(cc grpc.ClientConnInterface) DatanodeServiceClient {
	return &datanodeServiceClient{cc}
}

func (c *datanodeServiceClient) UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*UpdateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrderResponse)
	err := c.cc.Invoke(ctx, DatanodeService_UpdateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, DatanodeService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datanodeServiceClient) GossipSync(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*GossipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GossipResponse)
	err := c.cc.Invoke(ctx, DatanodeService_GossipSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatanodeServiceServer is the server API for DatanodeService service.
// All implementations must embed UnimplementedDatanodeServiceServer
// for forward compatibility.
type DatanodeServiceServer interface {
	// El Broker o el Gateway envían actualizaciones a un Datanode
	UpdateOrder(context.Context, *UpdateOrderRequest) (*UpdateOrderResponse, error)
	// El Gateway lee el estado desde un Datanode específico
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	// Sincronización entre pares (Gossip)
	GossipSync(context.Context, *GossipRequest) (*GossipResponse, error)
	mustEmbedUnimplementedDatanodeServiceServer()
}

// UnimplementedDatanodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatanodeServiceServer struct{}

func (UnimplementedDatanodeServiceServer) UpdateOrder(context.Context, *UpdateOrderRequest) (*UpdateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrder not implemented")
}
func (UnimplementedDatanodeServiceServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedDatanodeServiceServer) GossipSync(context.Context, *GossipRequest) (*GossipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GossipSync not implemented")
}
func (UnimplementedDatanodeServiceServer) mustEmbedUnimplementedDatanodeServiceServer() {}
func (UnimplementedDatanodeServiceServer) testEmbeddedByValue()                         {}

// UnsafeDatanodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatanodeServiceServer will
// result in compilation errors.
type UnsafeDatanodeServiceServer interface {
	mustEmbedUnimplementedDatanodeServiceServer()
}

func RegisterDatanodeServiceServer(s grpc.ServiceRegistrar, srv DatanodeServiceServer) {
	// If the following call panics, it indicates UnimplementedDatanodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatanodeService_ServiceDesc, srv)
}

func _DatanodeService_UpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).UpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_UpdateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).UpdateOrder(ctx, req.(*UpdateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatanodeService_GossipSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatanodeServiceServer).GossipSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatanodeService_GossipSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatanodeServiceServer).GossipSync(ctx, req.(*GossipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatanodeService_ServiceDesc is the grpc.ServiceDesc for DatanodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatanodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distrieats.DatanodeService",
	HandlerType: (*DatanodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateOrder",
			Handler:    _DatanodeService_UpdateOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _DatanodeService_GetOrder_Handler,
		},
		{
			MethodName: "GossipSync",
			Handler:    _DatanodeService_GossipSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/distrieats.proto",
}
