// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: proto/distrieats.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VectorClock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clocks map[string]int32 `protobuf:"bytes,1,rep,name=clocks,proto3" json:"clocks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // Mapa de Nodo -> Valor del Reloj
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{0}
}

func (x *VectorClock) GetClocks() map[string]int32 {
	if x != nil {
		return x.Clocks
	}
	return nil
}

type Pedido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Estado      string       `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"` // Recibido, Preparando, En Camino, Entregado, Cancelado
	VectorClock *VectorClock `protobuf:"bytes,3,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
}

func (x *Pedido) Reset() {
	*x = Pedido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pedido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pedido) ProtoMessage() {}

func (x *Pedido) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pedido.ProtoReflect.Descriptor instead.
func (*Pedido) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{1}
}

func (x *Pedido) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pedido) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *Pedido) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type CrearPedidoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClienteId string `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	PedidoId  string `protobuf:"bytes,2,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"` // ID único para idempotencia
}

func (x *CrearPedidoRequest) Reset() {
	*x = CrearPedidoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrearPedidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearPedidoRequest) ProtoMessage() {}

func (x *CrearPedidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearPedidoRequest.ProtoReflect.Descriptor instead.
func (*CrearPedidoRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{2}
}

func (x *CrearPedidoRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *CrearPedidoRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

type CrearPedidoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exito            bool   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje          string `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	DatanodeAsignado string `protobuf:"bytes,3,opt,name=datanode_asignado,json=datanodeAsignado,proto3" json:"datanode_asignado,omitempty"` // Útil para debug o validación
}

func (x *CrearPedidoResponse) Reset() {
	*x = CrearPedidoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrearPedidoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearPedidoResponse) ProtoMessage() {}

func (x *CrearPedidoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearPedidoResponse.ProtoReflect.Descriptor instead.
func (*CrearPedidoResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{3}
}

func (x *CrearPedidoResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *CrearPedidoResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *CrearPedidoResponse) GetDatanodeAsignado() string {
	if x != nil {
		return x.DatanodeAsignado
	}
	return ""
}

type ConsultarEstadoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClienteId string `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	PedidoId  string `protobuf:"bytes,2,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
}

func (x *ConsultarEstadoRequest) Reset() {
	*x = ConsultarEstadoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsultarEstadoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEstadoRequest) ProtoMessage() {}

func (x *ConsultarEstadoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEstadoRequest.ProtoReflect.Descriptor instead.
func (*ConsultarEstadoRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{4}
}

func (x *ConsultarEstadoRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *ConsultarEstadoRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

type ConsultarEstadoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encontrado         bool    `protobuf:"varint,1,opt,name=encontrado,proto3" json:"encontrado,omitempty"`
	Pedido             *Pedido `protobuf:"bytes,2,opt,name=pedido,proto3" json:"pedido,omitempty"`
	DatanodeConsultado string  `protobuf:"bytes,3,opt,name=datanode_consultado,json=datanodeConsultado,proto3" json:"datanode_consultado,omitempty"`
}

func (x *ConsultarEstadoResponse) Reset() {
	*x = ConsultarEstadoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsultarEstadoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEstadoResponse) ProtoMessage() {}

func (x *ConsultarEstadoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEstadoResponse.ProtoReflect.Descriptor instead.
func (*ConsultarEstadoResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{5}
}

func (x *ConsultarEstadoResponse) GetEncontrado() bool {
	if x != nil {
		return x.Encontrado
	}
	return false
}

func (x *ConsultarEstadoResponse) GetPedido() *Pedido {
	if x != nil {
		return x.Pedido
	}
	return nil
}

func (x *ConsultarEstadoResponse) GetDatanodeConsultado() string {
	if x != nil {
		return x.DatanodeConsultado
	}
	return ""
}

type ReportarValidacionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClienteId  string `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	PedidoId   string `protobuf:"bytes,2,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	DatanodeId string `protobuf:"bytes,3,opt,name=datanode_id,json=datanodeId,proto3" json:"datanode_id,omitempty"`
}

func (x *ReportarValidacionRequest) Reset() {
	*x = ReportarValidacionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportarValidacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportarValidacionRequest) ProtoMessage() {}

func (x *ReportarValidacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportarValidacionRequest.ProtoReflect.Descriptor instead.
func (*ReportarValidacionRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{6}
}

func (x *ReportarValidacionRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *ReportarValidacionRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

func (x *ReportarValidacionRequest) GetDatanodeId() string {
	if x != nil {
		return x.DatanodeId
	}
	return ""
}

type ReportarValidacionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exito bool `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
}

func (x *ReportarValidacionResponse) Reset() {
	*x = ReportarValidacionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportarValidacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportarValidacionResponse) ProtoMessage() {}

func (x *ReportarValidacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportarValidacionResponse.ProtoReflect.Descriptor instead.
func (*ReportarValidacionResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{7}
}

func (x *ReportarValidacionResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

type GetAllOrdersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllOrdersRequest) Reset() {
	*x = GetAllOrdersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOrdersRequest) ProtoMessage() {}

func (x *GetAllOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetAllOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{8}
}

type GetAllOrdersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pedidos map[string]*Pedido `protobuf:"bytes,1,rep,name=pedidos,proto3" json:"pedidos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetAllOrdersResponse) Reset() {
	*x = GetAllOrdersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOrdersResponse) ProtoMessage() {}

func (x *GetAllOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetAllOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllOrdersResponse) GetPedidos() map[string]*Pedido {
	if x != nil {
		return x.Pedidos
	}
	return nil
}

type UpdateOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pedido *Pedido `protobuf:"bytes,1,opt,name=pedido,proto3" json:"pedido,omitempty"`
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateOrderRequest) GetPedido() *Pedido {
	if x != nil {
		return x.Pedido
	}
	return nil
}

type UpdateOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exito   bool   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje string `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *UpdateOrderResponse) Reset() {
	*x = UpdateOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderResponse) ProtoMessage() {}

func (x *UpdateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateOrderResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *UpdateOrderResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PedidoId string `protobuf:"bytes,1,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrderRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encontrado bool    `protobuf:"varint,1,opt,name=encontrado,proto3" json:"encontrado,omitempty"`
	Pedido     *Pedido `protobuf:"bytes,2,opt,name=pedido,proto3" json:"pedido,omitempty"`
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrderResponse) GetEncontrado() bool {
	if x != nil {
		return x.Encontrado
	}
	return false
}

func (x *GetOrderResponse) GetPedido() *Pedido {
	if x != nil {
		return x.Pedido
	}
	return nil
}

// Mensaje para intercambiar todo el estado local en el protocolo Gossip
type GossipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DatanodeId string             `protobuf:"bytes,1,opt,name=datanode_id,json=datanodeId,proto3" json:"datanode_id,omitempty"`
	Pedidos    map[string]*Pedido `protobuf:"bytes,2,rep,name=pedidos,proto3" json:"pedidos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // Estado actual de los pedidos en este nodo
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{14}
}

func (x *GossipRequest) GetDatanodeId() string {
	if x != nil {
		return x.DatanodeId
	}
	return ""
}

func (x *GossipRequest) GetPedidos() map[string]*Pedido {
	if x != nil {
		return x.Pedidos
	}
	return nil
}

type GossipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exito   bool               `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Pedidos map[string]*Pedido `protobuf:"bytes,2,rep,name=pedidos,proto3" json:"pedidos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // El nodo receptor también puede enviar su estado para sincronización bidireccional si se desea
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_distrieats_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{15}
}

func (x *GossipResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *GossipResponse) GetPedidos() map[string]*Pedido {
	if x != nil {
		return x.Pedidos
	}
	return nil
}

var File_proto_distrieats_proto protoreflect.FileDescriptor

var file_proto_distrieats_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61,
	0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x65, 0x61, 0x74, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x0b, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x43,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x3b, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74,
	0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x43, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x6c, 0x0a, 0x06,
	0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x3a,
	0x0a, 0x0c, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74,
	0x73, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0b, 0x76,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x50, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x49, 0x64, 0x22, 0x72, 0x0a, 0x13,
	0x43, 0x72, 0x65, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x69, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x69, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e,
	0x73, 0x61, 0x6a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73,
	0x61, 0x6a, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x61, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x64, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x64, 0x6f,
	0x22, 0x54, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x72, 0x45, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x65, 0x64,
	0x69, 0x64, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x65,
	0x64, 0x69, 0x64, 0x6f, 0x49, 0x64, 0x22, 0x96, 0x01, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6c, 0x74, 0x61, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x64, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x64, 0x6f, 0x12, 0x2a, 0x0a, 0x06, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74, 0x73, 0x2e,
	0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x52, 0x06, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x12, 0x2f,
	0x0a, 0x13, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x75,
	0x6c, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x64, 0x61, 0x74,
	0x61, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x22,
	0x78, 0x0a, 0x19, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x63, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x65, 0x64, 0x69, 0x64, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64,
	0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x1a, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x69, 0x74, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x69, 0x74, 0x6f, 0x22, 0x15, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0xaf, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a,
	0x07, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d,
	0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x70,
	0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x1a, 0x4e, 0x0a, 0x0c, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x65, 0x61, 0x74, 0x73, 0x2e, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x40, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x06,
	0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74, 0x73, 0x2e, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f,
	0x52, 0x06, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x22, 0x45, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x78, 0x69, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x65, 0x78, 0x69, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x22,
	0x2e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x49, 0x64, 0x22,
	0x5e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x64,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x64, 0x6f, 0x12, 0x2a, 0x0a, 0x06, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74, 0x73,
	0x2e, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x52, 0x06, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x22,
	0xc2, 0x01, 0x0a, 0x0d, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x12, 0x40, 0x0a, 0x07, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74, 0x73,
	0x2e, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50,
	0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x70, 0x65, 0x64,
	0x69, 0x64, 0x6f, 0x73, 0x1a, 0x4e, 0x0a, 0x0c, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61,
	0x74, 0x73, 0x2e, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0xb9, 0x01, 0x0a, 0x0e, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x69, 0x74, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x69, 0x74, 0x6f, 0x12, 0x41, 0x0a,
	0x07, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x6f, 0x73, 0x73,
	0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x65, 0x64, 0x69, 0x64,
	0x6f, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73,
	0x1a, 0x4e, 0x0a, 0x0c, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74, 0x73, 0x2e, 0x50,
	0x65, 0x64, 0x69, 0x64, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x32, 0xa0, 0x02, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64,
	0x6f, 0x12, 0x1e, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74, 0x73, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74, 0x73, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x5a, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x72, 0x45,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x22, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61,
	0x74, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x72, 0x45, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x65, 0x61, 0x74, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x72,
	0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63,
	0x0a, 0x12, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x63, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74,
	0x73, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x63, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x64, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x61,
	0x72, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0xc0, 0x02, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65,
	0x61, 0x74, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65,
	0x61, 0x74, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x0a, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x19, 0x2e, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x65, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x12, 0x1f, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x65, 0x61, 0x74,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x65, 0x61, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_distrieats_proto_rawDescOnce sync.Once
	file_proto_distrieats_proto_rawDescData = file_proto_distrieats_proto_rawDesc
)

func file_proto_distrieats_proto_rawDescGZIP() []byte {
	file_proto_distrieats_proto_rawDescOnce.Do(func() {
		file_proto_distrieats_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_distrieats_proto_rawDescData)
	})
	return file_proto_distrieats_proto_rawDescData
}

var file_proto_distrieats_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_distrieats_proto_goTypes = []interface{}{
	(*VectorClock)(nil),                // 0: distrieats.VectorClock
	(*Pedido)(nil),                     // 1: distrieats.Pedido
	(*CrearPedidoRequest)(nil),         // 2: distrieats.CrearPedidoRequest
	(*CrearPedidoResponse)(nil),        // 3: distrieats.CrearPedidoResponse
	(*ConsultarEstadoRequest)(nil),     // 4: distrieats.ConsultarEstadoRequest
	(*ConsultarEstadoResponse)(nil),    // 5: distrieats.ConsultarEstadoResponse
	(*ReportarValidacionRequest)(nil),  // 6: distrieats.ReportarValidacionRequest
	(*ReportarValidacionResponse)(nil), // 7: distrieats.ReportarValidacionResponse
	(*GetAllOrdersRequest)(nil),        // 8: distrieats.GetAllOrdersRequest
	(*GetAllOrdersResponse)(nil),       // 9: distrieats.GetAllOrdersResponse
	(*UpdateOrderRequest)(nil),         // 10: distrieats.UpdateOrderRequest
	(*UpdateOrderResponse)(nil),        // 11: distrieats.UpdateOrderResponse
	(*GetOrderRequest)(nil),            // 12: distrieats.GetOrderRequest
	(*GetOrderResponse)(nil),           // 13: distrieats.GetOrderResponse
	(*GossipRequest)(nil),              // 14: distrieats.GossipRequest
	(*GossipResponse)(nil),             // 15: distrieats.GossipResponse
	nil,                                // 16: distrieats.VectorClock.ClocksEntry
	nil,                                // 17: distrieats.GetAllOrdersResponse.PedidosEntry
	nil,                                // 18: distrieats.GossipRequest.PedidosEntry
	nil,                                // 19: distrieats.GossipResponse.PedidosEntry
}
var file_proto_distrieats_proto_depIdxs = []int32{
	16, // 0: distrieats.VectorClock.clocks:type_name -> distrieats.VectorClock.ClocksEntry
	0,  // 1: distrieats.Pedido.vector_clock:type_name -> distrieats.VectorClock
	1,  // 2: distrieats.ConsultarEstadoResponse.pedido:type_name -> distrieats.Pedido
	17, // 3: distrieats.GetAllOrdersResponse.pedidos:type_name -> distrieats.GetAllOrdersResponse.PedidosEntry
	1,  // 4: distrieats.UpdateOrderRequest.pedido:type_name -> distrieats.Pedido
	1,  // 5: distrieats.GetOrderResponse.pedido:type_name -> distrieats.Pedido
	18, // 6: distrieats.GossipRequest.pedidos:type_name -> distrieats.GossipRequest.PedidosEntry
	19, // 7: distrieats.GossipResponse.pedidos:type_name -> distrieats.GossipResponse.PedidosEntry
	1,  // 8: distrieats.GetAllOrdersResponse.PedidosEntry.value:type_name -> distrieats.Pedido
	1,  // 9: distrieats.GossipRequest.PedidosEntry.value:type_name -> distrieats.Pedido
	1,  // 10: distrieats.GossipResponse.PedidosEntry.value:type_name -> distrieats.Pedido
	2,  // 11: distrieats.ClientService.CrearPedido:input_type -> distrieats.CrearPedidoRequest
	4,  // 12: distrieats.ClientService.ConsultarEstado:input_type -> distrieats.ConsultarEstadoRequest
	6,  // 13: distrieats.ClientService.ReportarValidacion:input_type -> distrieats.ReportarValidacionRequest
	10, // 14: distrieats.DatanodeService.UpdateOrder:input_type -> distrieats.UpdateOrderRequest
	12, // 15: distrieats.DatanodeService.GetOrder:input_type -> distrieats.GetOrderRequest
	14, // 16: distrieats.DatanodeService.GossipSync:input_type -> distrieats.GossipRequest
	8,  // 17: distrieats.DatanodeService.GetAllOrders:input_type -> distrieats.GetAllOrdersRequest
	3,  // 18: distrieats.ClientService.CrearPedido:output_type -> distrieats.CrearPedidoResponse
	5,  // 19: distrieats.ClientService.ConsultarEstado:output_type -> distrieats.ConsultarEstadoResponse
	7,  // 20: distrieats.ClientService.ReportarValidacion:output_type -> distrieats.ReportarValidacionResponse
	11, // 21: distrieats.DatanodeService.UpdateOrder:output_type -> distrieats.UpdateOrderResponse
	13, // 22: distrieats.DatanodeService.GetOrder:output_type -> distrieats.GetOrderResponse
	15, // 23: distrieats.DatanodeService.GossipSync:output_type -> distrieats.GossipResponse
	9,  // 24: distrieats.DatanodeService.GetAllOrders:output_type -> distrieats.GetAllOrdersResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_distrieats_proto_init() }
func file_proto_distrieats_proto_init() {
	if File_proto_distrieats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_distrieats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorClock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_distrieats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pedido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_distrieats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrearPedidoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_distrieats_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrearPedidoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_distrieats_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsultarEstadoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_distrieats_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsultarEstadoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_distrieats_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportarValidacionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_distrieats_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportarValidacionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_distrieats_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllOrdersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_distrieats_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllOrdersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_distrieats_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_distrieats_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_distrieats_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_distrieats_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_distrieats_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_distrieats_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_distrieats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_distrieats_proto_goTypes,
		DependencyIndexes: file_proto_distrieats_proto_depIdxs,
		MessageInfos:      file_proto_distrieats_proto_msgTypes,
	}.Build()
	File_proto_distrieats_proto = out.File
	file_proto_distrieats_proto_rawDesc = nil
	file_proto_distrieats_proto_goTypes = nil
	file_proto_distrieats_proto_depIdxs = nil
}
