// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/distrieats.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clocks        map[string]int32       `protobuf:"bytes,1,rep,name=clocks,proto3" json:"clocks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Mapa de Nodo -> Valor del Reloj
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_proto_distrieats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{0}
}

func (x *VectorClock) GetClocks() map[string]int32 {
	if x != nil {
		return x.Clocks
	}
	return nil
}

type Pedido struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Estado        string                 `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"` // Recibido, Preparando, En Camino, Entregado, Cancelado
	VectorClock   *VectorClock           `protobuf:"bytes,3,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pedido) Reset() {
	*x = Pedido{}
	mi := &file_proto_distrieats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pedido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pedido) ProtoMessage() {}

func (x *Pedido) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pedido.ProtoReflect.Descriptor instead.
func (*Pedido) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{1}
}

func (x *Pedido) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pedido) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *Pedido) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type CrearPedidoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     string                 `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	PedidoId      string                 `protobuf:"bytes,2,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"` // ID único para idempotencia
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearPedidoRequest) Reset() {
	*x = CrearPedidoRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearPedidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearPedidoRequest) ProtoMessage() {}

func (x *CrearPedidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearPedidoRequest.ProtoReflect.Descriptor instead.
func (*CrearPedidoRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{2}
}

func (x *CrearPedidoRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *CrearPedidoRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

type CrearPedidoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Exito            bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje          string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	DatanodeAsignado string                 `protobuf:"bytes,3,opt,name=datanode_asignado,json=datanodeAsignado,proto3" json:"datanode_asignado,omitempty"` // Útil para debug o validación
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CrearPedidoResponse) Reset() {
	*x = CrearPedidoResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearPedidoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearPedidoResponse) ProtoMessage() {}

func (x *CrearPedidoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearPedidoResponse.ProtoReflect.Descriptor instead.
func (*CrearPedidoResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{3}
}

func (x *CrearPedidoResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *CrearPedidoResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *CrearPedidoResponse) GetDatanodeAsignado() string {
	if x != nil {
		return x.DatanodeAsignado
	}
	return ""
}

type ConsultarEstadoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     string                 `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	PedidoId      string                 `protobuf:"bytes,2,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarEstadoRequest) Reset() {
	*x = ConsultarEstadoRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarEstadoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEstadoRequest) ProtoMessage() {}

func (x *ConsultarEstadoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEstadoRequest.ProtoReflect.Descriptor instead.
func (*ConsultarEstadoRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{4}
}

func (x *ConsultarEstadoRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *ConsultarEstadoRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

type ConsultarEstadoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Encontrado         bool                   `protobuf:"varint,1,opt,name=encontrado,proto3" json:"encontrado,omitempty"`
	Pedido             *Pedido                `protobuf:"bytes,2,opt,name=pedido,proto3" json:"pedido,omitempty"`
	DatanodeConsultado string                 `protobuf:"bytes,3,opt,name=datanode_consultado,json=datanodeConsultado,proto3" json:"datanode_consultado,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConsultarEstadoResponse) Reset() {
	*x = ConsultarEstadoResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarEstadoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEstadoResponse) ProtoMessage() {}

func (x *ConsultarEstadoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEstadoResponse.ProtoReflect.Descriptor instead.
func (*ConsultarEstadoResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{5}
}

func (x *ConsultarEstadoResponse) GetEncontrado() bool {
	if x != nil {
		return x.Encontrado
	}
	return false
}

func (x *ConsultarEstadoResponse) GetPedido() *Pedido {
	if x != nil {
		return x.Pedido
	}
	return nil
}

func (x *ConsultarEstadoResponse) GetDatanodeConsultado() string {
	if x != nil {
		return x.DatanodeConsultado
	}
	return ""
}

type ReportarValidacionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     string                 `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	PedidoId      string                 `protobuf:"bytes,2,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	DatanodeId    string                 `protobuf:"bytes,3,opt,name=datanode_id,json=datanodeId,proto3" json:"datanode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportarValidacionRequest) Reset() {
	*x = ReportarValidacionRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportarValidacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportarValidacionRequest) ProtoMessage() {}

func (x *ReportarValidacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportarValidacionRequest.ProtoReflect.Descriptor instead.
func (*ReportarValidacionRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{6}
}

func (x *ReportarValidacionRequest) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

func (x *ReportarValidacionRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

func (x *ReportarValidacionRequest) GetDatanodeId() string {
	if x != nil {
		return x.DatanodeId
	}
	return ""
}

type ReportarValidacionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportarValidacionResponse) Reset() {
	*x = ReportarValidacionResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportarValidacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportarValidacionResponse) ProtoMessage() {}

func (x *ReportarValidacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportarValidacionResponse.ProtoReflect.Descriptor instead.
func (*ReportarValidacionResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{7}
}

func (x *ReportarValidacionResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

type GetAllOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllOrdersRequest) Reset() {
	*x = GetAllOrdersRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOrdersRequest) ProtoMessage() {}

func (x *GetAllOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetAllOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{8}
}

type GetAllOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pedidos       map[string]*Pedido     `protobuf:"bytes,1,rep,name=pedidos,proto3" json:"pedidos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllOrdersResponse) Reset() {
	*x = GetAllOrdersResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOrdersResponse) ProtoMessage() {}

func (x *GetAllOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetAllOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllOrdersResponse) GetPedidos() map[string]*Pedido {
	if x != nil {
		return x.Pedidos
	}
	return nil
}

type UpdateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pedido        *Pedido                `protobuf:"bytes,1,opt,name=pedido,proto3" json:"pedido,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateOrderRequest) GetPedido() *Pedido {
	if x != nil {
		return x.Pedido
	}
	return nil
}

type UpdateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderResponse) Reset() {
	*x = UpdateOrderResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderResponse) ProtoMessage() {}

func (x *UpdateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateOrderResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *UpdateOrderResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PedidoId      string                 `protobuf:"bytes,1,opt,name=pedido_id,json=pedidoId,proto3" json:"pedido_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrderRequest) GetPedidoId() string {
	if x != nil {
		return x.PedidoId
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encontrado    bool                   `protobuf:"varint,1,opt,name=encontrado,proto3" json:"encontrado,omitempty"`
	Pedido        *Pedido                `protobuf:"bytes,2,opt,name=pedido,proto3" json:"pedido,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrderResponse) GetEncontrado() bool {
	if x != nil {
		return x.Encontrado
	}
	return false
}

func (x *GetOrderResponse) GetPedido() *Pedido {
	if x != nil {
		return x.Pedido
	}
	return nil
}

// Mensaje para intercambiar todo el estado local en el protocolo Gossip
type GossipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatanodeId    string                 `protobuf:"bytes,1,opt,name=datanode_id,json=datanodeId,proto3" json:"datanode_id,omitempty"`
	Pedidos       map[string]*Pedido     `protobuf:"bytes,2,rep,name=pedidos,proto3" json:"pedidos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Estado actual de los pedidos en este nodo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_proto_distrieats_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{14}
}

func (x *GossipRequest) GetDatanodeId() string {
	if x != nil {
		return x.DatanodeId
	}
	return ""
}

func (x *GossipRequest) GetPedidos() map[string]*Pedido {
	if x != nil {
		return x.Pedidos
	}
	return nil
}

type GossipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Pedidos       map[string]*Pedido     `protobuf:"bytes,2,rep,name=pedidos,proto3" json:"pedidos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // El nodo receptor también puede enviar su estado para sincronización bidireccional si se desea
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_proto_distrieats_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_distrieats_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_proto_distrieats_proto_rawDescGZIP(), []int{15}
}

func (x *GossipResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *GossipResponse) GetPedidos() map[string]*Pedido {
	if x != nil {
		return x.Pedidos
	}
	return nil
}

var File_proto_distrieats_proto protoreflect.FileDescriptor

const file_proto_distrieats_proto_rawDesc = "" +
	"\n" +
	"\x16proto/distrieats.proto\x12\n" +
	"distrieats\"\x85\x01\n" +
	"\vVectorClock\x12;\n" +
	"\x06clocks\x18\x01 \x03(\v2#.distrieats.VectorClock.ClocksEntryR\x06clocks\x1a9\n" +
	"\vClocksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"l\n" +
	"\x06Pedido\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06estado\x18\x02 \x01(\tR\x06estado\x12:\n" +
	"\fvector_clock\x18\x03 \x01(\v2\x17.distrieats.VectorClockR\vvectorClock\"P\n" +
	"\x12CrearPedidoRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\tR\tclienteId\x12\x1b\n" +
	"\tpedido_id\x18\x02 \x01(\tR\bpedidoId\"r\n" +
	"\x13CrearPedidoResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12+\n" +
	"\x11datanode_asignado\x18\x03 \x01(\tR\x10datanodeAsignado\"T\n" +
	"\x16ConsultarEstadoRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\tR\tclienteId\x12\x1b\n" +
	"\tpedido_id\x18\x02 \x01(\tR\bpedidoId\"\x96\x01\n" +
	"\x17ConsultarEstadoResponse\x12\x1e\n" +
	"\n" +
	"encontrado\x18\x01 \x01(\bR\n" +
	"encontrado\x12*\n" +
	"\x06pedido\x18\x02 \x01(\v2\x12.distrieats.PedidoR\x06pedido\x12/\n" +
	"\x13datanode_consultado\x18\x03 \x01(\tR\x12datanodeConsultado\"x\n" +
	"\x19ReportarValidacionRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\tR\tclienteId\x12\x1b\n" +
	"\tpedido_id\x18\x02 \x01(\tR\bpedidoId\x12\x1f\n" +
	"\vdatanode_id\x18\x03 \x01(\tR\n" +
	"datanodeId\"2\n" +
	"\x1aReportarValidacionResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\"\x15\n" +
	"\x13GetAllOrdersRequest\"\xaf\x01\n" +
	"\x14GetAllOrdersResponse\x12G\n" +
	"\apedidos\x18\x01 \x03(\v2-.distrieats.GetAllOrdersResponse.PedidosEntryR\apedidos\x1aN\n" +
	"\fPedidosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.distrieats.PedidoR\x05value:\x028\x01\"@\n" +
	"\x12UpdateOrderRequest\x12*\n" +
	"\x06pedido\x18\x01 \x01(\v2\x12.distrieats.PedidoR\x06pedido\"E\n" +
	"\x13UpdateOrderResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\".\n" +
	"\x0fGetOrderRequest\x12\x1b\n" +
	"\tpedido_id\x18\x01 \x01(\tR\bpedidoId\"^\n" +
	"\x10GetOrderResponse\x12\x1e\n" +
	"\n" +
	"encontrado\x18\x01 \x01(\bR\n" +
	"encontrado\x12*\n" +
	"\x06pedido\x18\x02 \x01(\v2\x12.distrieats.PedidoR\x06pedido\"\xc2\x01\n" +
	"\rGossipRequest\x12\x1f\n" +
	"\vdatanode_id\x18\x01 \x01(\tR\n" +
	"datanodeId\x12@\n" +
	"\apedidos\x18\x02 \x03(\v2&.distrieats.GossipRequest.PedidosEntryR\apedidos\x1aN\n" +
	"\fPedidosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.distrieats.PedidoR\x05value:\x028\x01\"\xb9\x01\n" +
	"\x0eGossipResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12A\n" +
	"\apedidos\x18\x02 \x03(\v2'.distrieats.GossipResponse.PedidosEntryR\apedidos\x1aN\n" +
	"\fPedidosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.distrieats.PedidoR\x05value:\x028\x012\xa0\x02\n" +
	"\rClientService\x12N\n" +
	"\vCrearPedido\x12\x1e.distrieats.CrearPedidoRequest\x1a\x1f.distrieats.CrearPedidoResponse\x12Z\n" +
	"\x0fConsultarEstado\x12\".distrieats.ConsultarEstadoRequest\x1a#.distrieats.ConsultarEstadoResponse\x12c\n" +
	"\x12ReportarValidacion\x12%.distrieats.ReportarValidacionRequest\x1a&.distrieats.ReportarValidacionResponse2\xc0\x02\n" +
	"\x0fDatanodeService\x12N\n" +
	"\vUpdateOrder\x12\x1e.distrieats.UpdateOrderRequest\x1a\x1f.distrieats.UpdateOrderResponse\x12E\n" +
	"\bGetOrder\x12\x1b.distrieats.GetOrderRequest\x1a\x1c.distrieats.GetOrderResponse\x12C\n" +
	"\n" +
	"GossipSync\x12\x19.distrieats.GossipRequest\x1a\x1a.distrieats.GossipResponse\x12Q\n" +
	"\fGetAllOrders\x12\x1f.distrieats.GetAllOrdersRequest\x1a .distrieats.GetAllOrdersResponseB\x12Z\x10distrieats/protob\x06proto3"

var (
	file_proto_distrieats_proto_rawDescOnce sync.Once
	file_proto_distrieats_proto_rawDescData []byte
)

func file_proto_distrieats_proto_rawDescGZIP() []byte {
	file_proto_distrieats_proto_rawDescOnce.Do(func() {
		file_proto_distrieats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_distrieats_proto_rawDesc), len(file_proto_distrieats_proto_rawDesc)))
	})
	return file_proto_distrieats_proto_rawDescData
}

var file_proto_distrieats_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_distrieats_proto_goTypes = []any{
	(*VectorClock)(nil),                // 0: distrieats.VectorClock
	(*Pedido)(nil),                     // 1: distrieats.Pedido
	(*CrearPedidoRequest)(nil),         // 2: distrieats.CrearPedidoRequest
	(*CrearPedidoResponse)(nil),        // 3: distrieats.CrearPedidoResponse
	(*ConsultarEstadoRequest)(nil),     // 4: distrieats.ConsultarEstadoRequest
	(*ConsultarEstadoResponse)(nil),    // 5: distrieats.ConsultarEstadoResponse
	(*ReportarValidacionRequest)(nil),  // 6: distrieats.ReportarValidacionRequest
	(*ReportarValidacionResponse)(nil), // 7: distrieats.ReportarValidacionResponse
	(*GetAllOrdersRequest)(nil),        // 8: distrieats.GetAllOrdersRequest
	(*GetAllOrdersResponse)(nil),       // 9: distrieats.GetAllOrdersResponse
	(*UpdateOrderRequest)(nil),         // 10: distrieats.UpdateOrderRequest
	(*UpdateOrderResponse)(nil),        // 11: distrieats.UpdateOrderResponse
	(*GetOrderRequest)(nil),            // 12: distrieats.GetOrderRequest
	(*GetOrderResponse)(nil),           // 13: distrieats.GetOrderResponse
	(*GossipRequest)(nil),              // 14: distrieats.GossipRequest
	(*GossipResponse)(nil),             // 15: distrieats.GossipResponse
	nil,                                // 16: distrieats.VectorClock.ClocksEntry
	nil,                                // 17: distrieats.GetAllOrdersResponse.PedidosEntry
	nil,                                // 18: distrieats.GossipRequest.PedidosEntry
	nil,                                // 19: distrieats.GossipResponse.PedidosEntry
}
var file_proto_distrieats_proto_depIdxs = []int32{
	16, // 0: distrieats.VectorClock.clocks:type_name -> distrieats.VectorClock.ClocksEntry
	0,  // 1: distrieats.Pedido.vector_clock:type_name -> distrieats.VectorClock
	1,  // 2: distrieats.ConsultarEstadoResponse.pedido:type_name -> distrieats.Pedido
	17, // 3: distrieats.GetAllOrdersResponse.pedidos:type_name -> distrieats.GetAllOrdersResponse.PedidosEntry
	1,  // 4: distrieats.UpdateOrderRequest.pedido:type_name -> distrieats.Pedido
	1,  // 5: distrieats.GetOrderResponse.pedido:type_name -> distrieats.Pedido
	18, // 6: distrieats.GossipRequest.pedidos:type_name -> distrieats.GossipRequest.PedidosEntry
	19, // 7: distrieats.GossipResponse.pedidos:type_name -> distrieats.GossipResponse.PedidosEntry
	1,  // 8: distrieats.GetAllOrdersResponse.PedidosEntry.value:type_name -> distrieats.Pedido
	1,  // 9: distrieats.GossipRequest.PedidosEntry.value:type_name -> distrieats.Pedido
	1,  // 10: distrieats.GossipResponse.PedidosEntry.value:type_name -> distrieats.Pedido
	2,  // 11: distrieats.ClientService.CrearPedido:input_type -> distrieats.CrearPedidoRequest
	4,  // 12: distrieats.ClientService.ConsultarEstado:input_type -> distrieats.ConsultarEstadoRequest
	6,  // 13: distrieats.ClientService.ReportarValidacion:input_type -> distrieats.ReportarValidacionRequest
	10, // 14: distrieats.DatanodeService.UpdateOrder:input_type -> distrieats.UpdateOrderRequest
	12, // 15: distrieats.DatanodeService.GetOrder:input_type -> distrieats.GetOrderRequest
	14, // 16: distrieats.DatanodeService.GossipSync:input_type -> distrieats.GossipRequest
	8,  // 17: distrieats.DatanodeService.GetAllOrders:input_type -> distrieats.GetAllOrdersRequest
	3,  // 18: distrieats.ClientService.CrearPedido:output_type -> distrieats.CrearPedidoResponse
	5,  // 19: distrieats.ClientService.ConsultarEstado:output_type -> distrieats.ConsultarEstadoResponse
	7,  // 20: distrieats.ClientService.ReportarValidacion:output_type -> distrieats.ReportarValidacionResponse
	11, // 21: distrieats.DatanodeService.UpdateOrder:output_type -> distrieats.UpdateOrderResponse
	13, // 22: distrieats.DatanodeService.GetOrder:output_type -> distrieats.GetOrderResponse
	15, // 23: distrieats.DatanodeService.GossipSync:output_type -> distrieats.GossipResponse
	9,  // 24: distrieats.DatanodeService.GetAllOrders:output_type -> distrieats.GetAllOrdersResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_distrieats_proto_init() }
func file_proto_distrieats_proto_init() {
	if File_proto_distrieats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_distrieats_proto_rawDesc), len(file_proto_distrieats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_distrieats_proto_goTypes,
		DependencyIndexes: file_proto_distrieats_proto_depIdxs,
		MessageInfos:      file_proto_distrieats_proto_msgTypes,
	}.Build()
	File_proto_distrieats_proto = out.File
	file_proto_distrieats_proto_goTypes = nil
	file_proto_distrieats_proto_depIdxs = nil
}
